module.exports = [
  { id: "s11", left: "Lento", right: "Rapidísimo" },
  { id: "s12", left: "Silencioso", right: "Escandaloso" },
  { id: "s13", left: "Ordenado", right: "Desastre total" },
  { id: "s14", left: "Fácil", right: "Imposible" },
  { id: "s15", left: "Realista", right: "Fantástico" },
  { id: "s16", left: "Amable", right: "Pesado" },
  { id: "s17", left: "Sano", right: "Pecado" },
  { id: "s18", left: "Elegante", right: "Charral" },
  { id: "s19", left: "Casero", right: "Fino" },
  { id: "s20", left: "Discreto", right: "Llamativo" },
  { id: "s21", left: "Simple", right: "Complicadísimo" },
  { id: "s22", left: "Relajado", right: "Acelerado" },
  { id: "s23", left: "Tradicional", right: "Innovador" },
  { id: "s24", left: "Atractivo", right: "Horrible" },
  { id: "s25", left: "Práctico", right: "Inservible" },
  { id: "s26", left: "Dulce", right: "Salado" },
  { id: "s27", left: "Amargo", right: "Rico" },
  { id: "s28", left: "Ligero", right: "Pesadísimo" },
  { id: "s29", left: "Seguro", right: "Riesgoso" },
  { id: "s30", left: "Decente", right: "Épico" },

  { id: "s31", left: "Caro para lo que es", right: "Valió cada colón" },
  { id: "s32", left: "Meh", right: "Una joya" },
  { id: "s33", left: "De viejitos", right: "De chamacos" },
  { id: "s34", left: "Muy formal", right: "Súper informal" },
  { id: "s35", left: "No lo recomiendo", right: "Recomendadísimo" },
  { id: "s36", left: "Poco común", right: "De toda la vida" },
  { id: "s37", left: "Cero útil", right: "Súper útil" },
  { id: "s38", left: "En serio", right: "Vacilón" },
  { id: "s39", left: "Apretado", right: "Holgado" },
  { id: "s40", left: "Frágil", right: "Indestructible" },

  { id: "s41", left: "Sabor suave", right: "Sabor fuerte" },
  { id: "s42", left: "Poco picante", right: "Picantísimo" },
  { id: "s43", left: "Comida de todos los días", right: "Para ocasión especial" },
  { id: "s44", left: "Se ve barato", right: "Se ve de lujo" },
  { id: "s45", left: "Cero romántico", right: "Súper romántico" },
  { id: "s46", left: "Para quedarse en casa", right: "Para salir" },
  { id: "s47", left: "Apto para niños", right: "Solo adultos" },
  { id: "s48", left: "De playa", right: "De montaña" },
  { id: "s49", left: "Muy tierno", right: "Muy rudo" },
  { id: "s50", left: "Me da pereza", right: "Me emociona" },

  { id: "s51", left: "Poca energía", right: "Energía full" },
  { id: "s52", left: "Conservador", right: "Atrevido" },
  { id: "s53", left: "Honesto", right: "Pura hablada" },
  { id: "s54", left: "Serio", right: "Payaso" },
  { id: "s55", left: "Cero drama", right: "Drama total" },
  { id: "s56", left: "Pacífico", right: "Violento" },
  { id: "s57", left: "Amistoso", right: "Antisocial" },
  { id: "s58", left: "Nervioso", right: "Confiadísimo" },
  { id: "s59", left: "Se nota", right: "No se nota" },
  { id: "s60", left: "Se siente natural", right: "Se siente forzado" },
];